name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "22874218-51cdd3a9-0ca8-424d-aec9-2f262f5c976c" -e "21637240-bda14597-974e-4b74-9766-73a668e0a3a3"
